/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/public/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              message: string
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/public/staff/application': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            user: {
              rut: string
              names: string
              lastName0: string
              lastName1: string
              /** Format: email */
              email: string
            }
            staff: Record<string, never>
          }
        }
      }
      responses: {
        /** @description No Content */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/public/student/application': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            user: {
              rut: string
              names: string
              lastName0: string
              lastName1: string
              /** Format: email */
              email: string
            }
            student: Record<string, never>
          }
        }
      }
      responses: {
        /** @description No Content */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/public/users/verify-then-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            rut: string
          }
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    trace?: never
  }
  '/api/private/students/applications': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              users: {
                /** Format: uuid */
                id: string
                names: string
                lastName0: string
                lastName1: string
                studentProfile: {
                  /** @enum {string} */
                  applicationState:
                    | 'ACCEPTED_AS_STUDENT'
                    | 'PENDING_AS_STUDENT'
                    | 'REJECTED_AS_STUDENT'
                }
              }[]
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/private/staff/applications': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              users: {
                /** Format: uuid */
                id: string
                names: string
                lastName0: string
                lastName1: string
                staffProfile: {
                  /** @enum {string} */
                  applicationState: 'ACCEPTED_AS_STAFF' | 'PENDING_AS_STAFF' | 'REJECTED_AS_STAFF'
                }
              }[]
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/private/student/application/:id': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              user: {
                /** Format: uuid */
                id: string
                auth0Id: string | null
                rut: string
                names: string
                lastName0: string
                lastName1: string
                /** Format: email */
                email: string
                /** Format: date */
                createdAt: string | null
                studentProfile: {
                  /** @enum {string} */
                  applicationState:
                    | 'PENDING_AS_STUDENT'
                    | 'PENDING_AS_STAFF'
                    | 'ACCEPTED_AS_STUDENT'
                    | 'ACCEPTED_AS_STAFF'
                    | 'CREATED'
                    | 'REJECTED_AS_STAFF'
                    | 'REJECTED_AS_STUDENT'
                    | 'ACTIVE'
                }
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/private/staff/application/:id': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              user: {
                /** Format: uuid */
                id: string
                auth0Id: string | null
                rut: string
                names: string
                lastName0: string
                lastName1: string
                /** Format: email */
                email: string
                /** Format: date */
                createdAt: string | null
                staffProfile: {
                  /** @enum {string} */
                  applicationState:
                    | 'PENDING_AS_STUDENT'
                    | 'PENDING_AS_STAFF'
                    | 'ACCEPTED_AS_STUDENT'
                    | 'ACCEPTED_AS_STAFF'
                    | 'CREATED'
                    | 'REJECTED_AS_STAFF'
                    | 'REJECTED_AS_STUDENT'
                    | 'ACTIVE'
                }
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/private/student/appstate/:applicationState/:id': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
          applicationState: 'PENDING_AS_STUDENT' | 'ACCEPTED_AS_STUDENT' | 'REJECTED_AS_STUDENT'
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    trace?: never
  }
  '/api/private/staff/appstate/:applicationState/:id': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
          applicationState: 'PENDING_AS_STAFF' | 'ACCEPTED_AS_STAFF' | 'REJECTED_AS_STAFF'
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    trace?: never
  }
  '/api/private/students/accepted': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              users: {
                /** Format: uuid */
                id: string
                names: string
                lastName0: string
                lastName1: string
              }[]
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/private/staff/accepted': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              users: {
                /** Format: uuid */
                id: string
                names: string
                lastName0: string
                lastName1: string
              }[]
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/private/job/students/create': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** Format: uuid */
              jobId: string
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/private/job/staff/create': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** Format: uuid */
              jobId: string
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/private/job/students/step/:jobId': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          jobId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              created: number
              haveErrors: number
              stepsAvailable: boolean
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/private/job/staff/step/:jobId': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          jobId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              created: number
              haveErrors: number
              stepsAvailable: boolean
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/private/job/status/:jobId': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          jobId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** @enum {string} */
              status: 'PENDING' | 'RUNNING' | 'DONE' | 'DONE_WITH_ERRORS'
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': string
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/favicon.ico': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/openapi.json': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
